services:
  - type: web
    name: student-performance-predictor
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y gcc python3-dev
      pip install --upgrade pip
      pip install wheel setuptools
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: MALLOC_TRIM_THRESHOLD_
        value: "65536"
      - key: PIP_NO_BINARY
        value: ":all:"
    plan: free
    env: python
    healthCheckPath: /
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1 